"""New 'jwt_token_pairs', resize(user) password:50->150, set_default(is_admin)=False

Revision ID: 6ba26199c74b
Revises: fb04496e5b2c
Create Date: 2025-07-03 23:23:17.021788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba26199c74b'
down_revision: Union[str, Sequence[str], None] = 'fb04496e5b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt_token_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('create_timestamp', sa.Integer(), nullable=False),
    sa.Column('update_timestamp', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=250), nullable=False),
    sa.Column('refresh_token', sa.String(length=250), nullable=False),
    sa.Column('access_token_expires_timestamp', sa.Integer(), nullable=False),
    sa.Column('refresh_token_expires_timestamp', sa.Integer(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_table('jwt_token_pairs')
    # ### end Alembic commands ###
