"""User add new field 'is_confirmed'

Revision ID: 8e57338f0abe
Revises: 6ba26199c74b
Create Date: 2025-07-13 23:50:14.948587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e57338f0abe'
down_revision: Union[str, Sequence[str], None] = '6ba26199c74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_confirmed", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_confirmed = false WHERE is_confirmed IS NULL")
    op.alter_column("users", "is_confirmed", nullable=False)
    op.alter_column("users", "is_confirmed", server_default=sa.text("false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_confirmed')
    # ### end Alembic commands ###
